// action types
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

//Near By Shows types
export const FETCH_NEARBY_SHOWS_REQUEST='FETCH_NEARBY_SHOWS_REQUEST';
export const FETCH_NEARBY_SHOWS_SUCCESS='FETCH_NEARBY_SHOWS_SUCCESS';
export const FETCH_NEARBY_SHOWS_FAILURE='FETCH_NEARBY_SHOWS_FAILURE';

//SingleShowByLocation
export const FETCH_SHOWBY_LOCATION_REQUEST='FETCH_SHOWBY_LOCATIONS_REQUEST';
export const FETCH_SHOWBY_LOCATION_SUCCESS='FETCH_SHOWBY_LOCATIONS_SUCCESS';
export const FETCH_SHOWBY_LOCATION_FAILURE='FETCH_SHOWBY_LOCATIONS_FAILURE';

//searchByTitleActions
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';

//shhowSearchAction
export const SET_SELECTED_SHOW = 'SET_SELECTED_SHOW';